name: Build Release
runs:
  using: composite
  steps:
    - name: Build Release
      shell: bash
      run:  ./mvnw --settings .mvn/release-settings.xml --no-transfer-progress --batch-mode clean deploy -DaltDeploymentRepository=local::file:deployment-repository -DskipTests
